#!/usr/bin/env python3
"""
Build per-layer, per-expert LoRA rank maps for pruned MoE models.

The script consumes:
1. A Shapley CSV generated by analysis/calc_shapley.py.
2. A selected_experts JSON generated by pruning/methods/select_by_shapley.py.

It outputs a rank_map JSON that can be converted into PEFT rank_pattern later.

Supported strategies:
- bucket:  contribution-aware bucket allocation.
- uniform: assign the same LoRA rank to every retained expert.
- random: randomly assign bucket ranks to retained experts for baseline comparison.
"""

import argparse
import json
import math
import os
import random
from dataclasses import dataclass
from typing import Dict, Iterable, List, Mapping, MutableMapping, Optional, Sequence, Tuple

import pandas as pd


DEFAULT_RANK_BUCKETS = [32, 16, 8]
DEFAULT_BUCKET_RATIOS = [0.2, 0.4, 0.4]
DEFAULT_UNIFORM_RANK = 16


@dataclass(frozen=True)
class RankMapStats:
    total_layers: int
    total_retained_experts: int
    average_rank: float
    min_rank: int
    max_rank: int


RankMap = Dict[str, Dict[str, int]]
SelectedExperts = Dict[str, List[int]]


def parse_int_list(raw: str) -> List[int]:
    values = [item.strip() for item in raw.split(",") if item.strip()]
    if not values:
        raise argparse.ArgumentTypeError("expected at least one integer")
    try:
        return [int(item) for item in values]
    except ValueError as exc:
        raise argparse.ArgumentTypeError(f"invalid integer list: {raw}") from exc


def parse_float_list(raw: str) -> List[float]:
    values = [item.strip() for item in raw.split(",") if item.strip()]
    if not values:
        raise argparse.ArgumentTypeError("expected at least one number")
    try:
        return [float(item) for item in values]
    except ValueError as exc:
        raise argparse.ArgumentTypeError(f"invalid number list: {raw}") from exc


def load_selected_experts(path: str) -> SelectedExperts:
    """Load selected experts and ignore metadata keys."""
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    selected: SelectedExperts = {}
    for layer, experts in data.items():
        if str(layer).startswith("_"):
            continue
        if not isinstance(experts, list):
            continue
        selected[str(int(layer))] = sorted({int(expert_id) for expert_id in experts})

    if not selected:
        raise ValueError(f"No selected expert layers found in {path}")

    return dict(sorted(selected.items(), key=lambda item: int(item[0])))


def load_shapley_scores(
    path: str,
    layer_col: str = "Layer",
    expert_col: str = "Expert_ID",
    score_col: str = "Shapley_Value",
) -> pd.DataFrame:
    """Load Shapley CSV and normalize required columns."""
    df = pd.read_csv(path)
    missing = [col for col in [layer_col, expert_col, score_col] if col not in df.columns]
    if missing:
        raise ValueError(f"Shapley CSV missing required columns: {missing}")

    df = df[[layer_col, expert_col, score_col]].copy()
    df = df.rename(
        columns={
            layer_col: "Layer",
            expert_col: "Expert_ID",
            score_col: "Shapley_Value",
        }
    )
    df["Layer"] = df["Layer"].astype(int)
    df["Expert_ID"] = df["Expert_ID"].astype(int)
    df["Shapley_Value"] = df["Shapley_Value"].astype(float)
    return df


def validate_bucket_config(rank_buckets: Sequence[int], bucket_ratios: Sequence[float]) -> None:
    if len(rank_buckets) != len(bucket_ratios):
        raise ValueError(
            "rank_buckets and bucket_ratios must have the same length: "
            f"{len(rank_buckets)} != {len(bucket_ratios)}"
        )
    if not rank_buckets:
        raise ValueError("rank_buckets cannot be empty")
    if any(rank <= 0 for rank in rank_buckets):
        raise ValueError(f"all ranks must be positive, got {list(rank_buckets)}")
    if any(ratio < 0 for ratio in bucket_ratios):
        raise ValueError(f"bucket ratios must be non-negative, got {list(bucket_ratios)}")
    ratio_sum = sum(bucket_ratios)
    if ratio_sum <= 0:
        raise ValueError("sum of bucket_ratios must be positive")
    if not math.isclose(ratio_sum, 1.0, rel_tol=1e-6, abs_tol=1e-6):
        raise ValueError(f"bucket_ratios must sum to 1.0, got {ratio_sum}")


def _bucket_sizes(total: int, ratios: Sequence[float]) -> List[int]:
    """Convert ratios into integer bucket sizes while preserving the total count."""
    if total <= 0:
        return [0 for _ in ratios]

    raw_sizes = [total * ratio for ratio in ratios]
    sizes = [int(math.floor(size)) for size in raw_sizes]

    remaining = total - sum(sizes)
    remainders = sorted(
        enumerate(raw_sizes),
        key=lambda item: (item[1] - math.floor(item[1]), -item[0]),
        reverse=True,
    )

    for idx, _ in remainders[:remaining]:
        sizes[idx] += 1

    return sizes


def ranks_from_buckets(
    expert_ids: Sequence[int],
    rank_buckets: Sequence[int],
    bucket_ratios: Sequence[float],
) -> Dict[int, int]:
    """Assign bucket ranks to experts in the provided order."""
    validate_bucket_config(rank_buckets, bucket_ratios)

    sizes = _bucket_sizes(len(expert_ids), bucket_ratios)
    rank_by_expert: Dict[int, int] = {}

    cursor = 0
    for rank, size in zip(rank_buckets, sizes):
        for expert_id in expert_ids[cursor : cursor + size]:
            rank_by_expert[int(expert_id)] = int(rank)
        cursor += size

    if cursor != len(expert_ids):
        raise RuntimeError("internal bucket allocation error")

    return rank_by_expert


def get_layer_scores(df: pd.DataFrame, layer_id: int) -> Mapping[int, float]:
    layer_df = df[df["Layer"] == int(layer_id)]
    if layer_df.empty:
        return {}

    # If duplicated rows exist, keep the largest score for deterministic behavior.
    grouped = layer_df.groupby("Expert_ID", as_index=True)["Shapley_Value"].max()
    return {int(expert_id): float(score) for expert_id, score in grouped.items()}


def sort_experts_by_contribution(
    expert_ids: Sequence[int],
    scores: Mapping[int, float],
    missing_score: float = 0.0,
) -> List[int]:
    """Sort experts by contribution descending, with Expert_ID as deterministic tie-breaker."""
    return sorted(
        [int(expert_id) for expert_id in expert_ids],
        key=lambda expert_id: (-float(scores.get(expert_id, missing_score)), expert_id),
    )


def build_rank_map(
    shapley_df: pd.DataFrame,
    selected_experts: Mapping[str, Sequence[int]],
    strategy: str = "bucket",
    rank_buckets: Sequence[int] = DEFAULT_RANK_BUCKETS,
    bucket_ratios: Sequence[float] = DEFAULT_BUCKET_RATIOS,
    uniform_rank: int = DEFAULT_UNIFORM_RANK,
    random_seed: int = 42,
    missing_score: float = 0.0,
) -> RankMap:
    """
    Build a rank map.

    Args:
        shapley_df: DataFrame with Layer, Expert_ID, Shapley_Value columns.
        selected_experts: {layer_id: [expert_id, ...]} for retained experts.
        strategy: bucket, uniform, or random.
        rank_buckets: ranks used by bucket/random strategies.
        bucket_ratios: bucket sizes used by bucket/random strategies.
        uniform_rank: rank used by uniform strategy.
        random_seed: seed for random baseline.
        missing_score: score assigned to retained experts missing from Shapley CSV.
    """
    strategy = strategy.lower()
    if strategy not in {"bucket", "uniform", "random"}:
        raise ValueError(f"Unsupported strategy: {strategy}")
    if uniform_rank <= 0:
        raise ValueError(f"uniform_rank must be positive, got {uniform_rank}")

    if strategy in {"bucket", "random"}:
        validate_bucket_config(rank_buckets, bucket_ratios)

    rng = random.Random(random_seed)
    rank_map: RankMap = {}

    for layer_key, expert_ids in sorted(selected_experts.items(), key=lambda item: int(item[0])):
        layer_id = int(layer_key)
        retained = sorted({int(expert_id) for expert_id in expert_ids})
        if not retained:
            continue

        if strategy == "uniform":
            layer_rank_map = {expert_id: int(uniform_rank) for expert_id in retained}
        else:
            layer_scores = get_layer_scores(shapley_df, layer_id)
            sorted_experts = sort_experts_by_contribution(
                retained,
                layer_scores,
                missing_score=missing_score,
            )

            if strategy == "random":
                shuffled = list(sorted_experts)
                rng.shuffle(shuffled)
                layer_rank_map = ranks_from_buckets(shuffled, rank_buckets, bucket_ratios)
            else:
                layer_rank_map = ranks_from_buckets(sorted_experts, rank_buckets, bucket_ratios)

        rank_map[str(layer_id)] = {
            str(expert_id): int(layer_rank_map[expert_id])
            for expert_id in sorted(layer_rank_map)
        }

    if not rank_map:
        raise ValueError("Generated empty rank_map")

    return rank_map


def collect_rank_stats(rank_map: Mapping[str, Mapping[str, int]]) -> RankMapStats:
    ranks = [
        int(rank)
        for layer_ranks in rank_map.values()
        for rank in layer_ranks.values()
    ]
    if not ranks:
        raise ValueError("rank_map contains no ranks")

    return RankMapStats(
        total_layers=len(rank_map),
        total_retained_experts=len(ranks),
        average_rank=sum(ranks) / len(ranks),
        min_rank=min(ranks),
        max_rank=max(ranks),
    )


def attach_metadata(
    rank_map: RankMap,
    *,
    strategy: str,
    shapley_csv: str,
    selected_experts: str,
    rank_buckets: Sequence[int],
    bucket_ratios: Sequence[float],
    uniform_rank: int,
    random_seed: int,
    score_col: str,
) -> MutableMapping[str, object]:
    stats = collect_rank_stats(rank_map)
    output: MutableMapping[str, object] = dict(rank_map)
    output["_metadata"] = {
        "method": "adaptive_lora_rank_map",
        "strategy": strategy,
        "shapley_csv": shapley_csv,
        "selected_experts": selected_experts,
        "score_column": score_col,
        "rank_buckets": list(rank_buckets),
        "bucket_ratios": list(bucket_ratios),
        "uniform_rank": int(uniform_rank),
        "random_seed": int(random_seed),
        "total_layers": stats.total_layers,
        "total_retained_experts": stats.total_retained_experts,
        "average_rank": stats.average_rank,
        "min_rank": stats.min_rank,
        "max_rank": stats.max_rank,
    }
    return output


def save_rank_map(output_path: str, data: Mapping[str, object]) -> None:
    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Build LoRA rank_map from Shapley scores and selected experts.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--shapley_csv", required=True, help="Path to Shapley CSV.")
    parser.add_argument("--selected_experts", required=True, help="Path to selected experts JSON.")
    parser.add_argument("--output", required=True, help="Output rank_map JSON path.")

    parser.add_argument(
        "--strategy",
        choices=["bucket", "uniform", "random"],
        default="bucket",
        help="Rank allocation strategy.",
    )
    parser.add_argument(
        "--rank_buckets",
        type=parse_int_list,
        default=DEFAULT_RANK_BUCKETS,
        help="Comma-separated ranks for bucket/random strategies.",
    )
    parser.add_argument(
        "--bucket_ratios",
        type=parse_float_list,
        default=DEFAULT_BUCKET_RATIOS,
        help="Comma-separated bucket ratios. Must sum to 1.",
    )
    parser.add_argument("--uniform_rank", type=int, default=DEFAULT_UNIFORM_RANK, help="Rank for uniform strategy.")
    parser.add_argument("--random_seed", type=int, default=42, help="Random seed for random strategy.")
    parser.add_argument(
        "--missing_score",
        type=float,
        default=0.0,
        help="Score assigned to retained experts missing from Shapley CSV.",
    )

    parser.add_argument("--layer_col", default="Layer", help="Layer column in Shapley CSV.")
    parser.add_argument("--expert_col", default="Expert_ID", help="Expert column in Shapley CSV.")
    parser.add_argument("--score_col", default="Shapley_Value", help="Score column in Shapley CSV.")
    return parser


def main() -> None:
    parser = build_arg_parser()
    args = parser.parse_args()

    shapley_df = load_shapley_scores(
        args.shapley_csv,
        layer_col=args.layer_col,
        expert_col=args.expert_col,
        score_col=args.score_col,
    )
    selected_experts = load_selected_experts(args.selected_experts)

    rank_map = build_rank_map(
        shapley_df=shapley_df,
        selected_experts=selected_experts,
        strategy=args.strategy,
        rank_buckets=args.rank_buckets,
        bucket_ratios=args.bucket_ratios,
        uniform_rank=args.uniform_rank,
        random_seed=args.random_seed,
        missing_score=args.missing_score,
    )

    output = attach_metadata(
        rank_map,
        strategy=args.strategy,
        shapley_csv=args.shapley_csv,
        selected_experts=args.selected_experts,
        rank_buckets=args.rank_buckets,
        bucket_ratios=args.bucket_ratios,
        uniform_rank=args.uniform_rank,
        random_seed=args.random_seed,
        score_col=args.score_col,
    )
    save_rank_map(args.output, output)

    stats = collect_rank_stats(rank_map)
    print("=" * 70)
    print("LoRA rank_map generated")
    print("=" * 70)
    print(f"Strategy:                 {args.strategy}")
    print(f"Output:                   {args.output}")
    print(f"Layers:                   {stats.total_layers}")
    print(f"Retained experts:          {stats.total_retained_experts}")
    print(f"Average rank:              {stats.average_rank:.2f}")
    print(f"Rank range:                {stats.min_rank} - {stats.max_rank}")
    print("=" * 70)


if __name__ == "__main__":
    main()
