#!/usr/bin/env python3
"""
Train LoRA adapters for pruned MoE models with expert-wise adaptive ranks.

The first implementation focuses on Qwen3-style MoE modules:

    model.layers.{layer}.mlp.experts.{expert}.gate_proj
    model.layers.{layer}.mlp.experts.{expert}.up_proj
    model.layers.{layer}.mlp.experts.{expert}.down_proj

The script reads a rank_map generated by finetune/build_rank_map.py and converts it
to PEFT rank_pattern / alpha_pattern, then trains a LoRA adapter with HuggingFace
Trainer.
"""

import argparse
import json
import logging
import math
import os
from dataclasses import dataclass
from typing import Dict, Iterable, List, Mapping, MutableMapping, Optional, Sequence

import torch
from torch.utils.data import Dataset


logger = logging.getLogger(__name__)


RankMap = Dict[str, Dict[str, int]]


QWEN3_EXPERT_MODULE_TEMPLATE = "model.layers.{layer}.mlp.experts.{expert}.{module}"
DEEPSEEK_EXPERT_MODULE_TEMPLATE = "model.layers.{layer}.mlp.experts.{expert}.{module}"


@dataclass
class TextExample:
    text: str


class CausalLMDataset(Dataset):
    """Simple tokenized dataset for causal language model fine-tuning."""

    def __init__(
        self,
        examples: Sequence[TextExample],
        tokenizer,
        max_seq_length: int,
        add_eos_token: bool = True,
    ):
        self.features = []
        for example in examples:
            text = example.text.strip()
            if not text:
                continue
            if add_eos_token and tokenizer.eos_token and not text.endswith(tokenizer.eos_token):
                text = text + tokenizer.eos_token

            encoded = tokenizer(
                text,
                truncation=True,
                max_length=max_seq_length,
                add_special_tokens=True,
            )
            input_ids = encoded["input_ids"]
            if not input_ids:
                continue

            self.features.append(
                {
                    "input_ids": input_ids,
                    "attention_mask": encoded["attention_mask"],
                    "labels": list(input_ids),
                }
            )

        if not self.features:
            raise ValueError("No usable training examples after tokenization.")

    def __len__(self) -> int:
        return len(self.features)

    def __getitem__(self, index: int) -> Mapping[str, List[int]]:
        return self.features[index]


class CausalLMDataCollator:
    """Pad input_ids/attention_mask/labels for causal LM training."""

    def __init__(self, tokenizer, label_pad_token_id: int = -100):
        self.tokenizer = tokenizer
        self.label_pad_token_id = label_pad_token_id

    def __call__(self, features: Sequence[Mapping[str, List[int]]]) -> Mapping[str, torch.Tensor]:
        max_len = max(len(feature["input_ids"]) for feature in features)
        pad_token_id = self.tokenizer.pad_token_id
        if pad_token_id is None:
            pad_token_id = self.tokenizer.eos_token_id

        batch = {
            "input_ids": [],
            "attention_mask": [],
            "labels": [],
        }

        for feature in features:
            length = len(feature["input_ids"])
            pad_len = max_len - length
            batch["input_ids"].append(feature["input_ids"] + [pad_token_id] * pad_len)
            batch["attention_mask"].append(feature["attention_mask"] + [0] * pad_len)
            batch["labels"].append(feature["labels"] + [self.label_pad_token_id] * pad_len)

        return {key: torch.tensor(value, dtype=torch.long) for key, value in batch.items()}


def setup_logging() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(levelname)s - %(name)s - %(message)s",
    )


def load_rank_map(path: str) -> RankMap:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    rank_map: RankMap = {}
    for layer, expert_ranks in data.items():
        if str(layer).startswith("_"):
            continue
        if not isinstance(expert_ranks, dict):
            continue

        normalized_layer = str(int(layer))
        rank_map[normalized_layer] = {
            str(int(expert_id)): int(rank)
            for expert_id, rank in expert_ranks.items()
            if int(rank) > 0
        }

    if not rank_map:
        raise ValueError(f"No layer rank entries found in rank_map: {path}")

    return dict(sorted(rank_map.items(), key=lambda item: int(item[0])))


def get_module_template(model_type: str) -> str:
    model_type = model_type.lower()
    if model_type == "qwen3":
        return QWEN3_EXPERT_MODULE_TEMPLATE
    if model_type == "deepseek":
        return DEEPSEEK_EXPERT_MODULE_TEMPLATE
    raise ValueError(
        f"Unsupported model_type '{model_type}'. The first version supports qwen3 only; "
        "deepseek is included for compatible module names, and gpt-oss needs a separate packed-expert adapter."
    )


def build_rank_pattern(
    model_type: str,
    rank_map: Mapping[str, Mapping[str, int]],
    target_modules: Sequence[str],
    alpha_scale: float = 2.0,
) -> tuple[Dict[str, int], Dict[str, int], List[str]]:
    """
    Convert expert rank_map to PEFT target_modules, rank_pattern and alpha_pattern.

    Only modules expanded from rank_map are passed to PEFT target_modules. This
    prevents zeroed/pruned experts from receiving LoRA parameters.
    """
    if alpha_scale <= 0:
        raise ValueError(f"alpha_scale must be positive, got {alpha_scale}")
    if not target_modules:
        raise ValueError("target_modules cannot be empty")

    module_template = get_module_template(model_type)
    rank_pattern: Dict[str, int] = {}
    alpha_pattern: Dict[str, int] = {}
    target_module_paths: List[str] = []

    for layer, expert_ranks in rank_map.items():
        for expert, rank in expert_ranks.items():
            rank = int(rank)
            if rank <= 0:
                continue

            alpha = max(1, int(round(rank * alpha_scale)))
            for module in target_modules:
                module_name = module_template.format(
                    layer=int(layer),
                    expert=int(expert),
                    module=module,
                )
                rank_pattern[module_name] = rank
                alpha_pattern[module_name] = alpha
                target_module_paths.append(module_name)

    if not rank_pattern:
        raise ValueError("Generated empty rank_pattern.")

    return rank_pattern, alpha_pattern, target_module_paths


def validate_lora_targets_exist(model, target_module_paths: Sequence[str]) -> None:
    """Fail early if rank_map-expanded LoRA targets do not exist in the loaded model."""
    available_modules = set(dict(model.named_modules()))
    missing = [module_name for module_name in target_module_paths if module_name not in available_modules]
    if missing:
        preview = ", ".join(missing[:5])
        raise ValueError(
            f"{len(missing)} LoRA target modules from rank_map were not found in the model. "
            f"First missing targets: {preview}"
        )


def parse_csv_list(raw: str) -> List[str]:
    values = [item.strip() for item in raw.split(",") if item.strip()]
    if not values:
        raise argparse.ArgumentTypeError("expected at least one value")
    return values


def read_json_or_jsonl(path: str) -> List[Mapping[str, object]]:
    if path.endswith(".jsonl"):
        records = []
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line:
                    records.append(json.loads(line))
        return records

    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)

    if isinstance(data, list):
        return data
    if isinstance(data, dict):
        for key in ["data", "train", "examples", "instances"]:
            if key in data and isinstance(data[key], list):
                return data[key]
        return [data]

    raise ValueError(f"Unsupported data format in {path}")


def format_messages(record: Mapping[str, object], tokenizer) -> Optional[str]:
    messages = record.get("messages")
    if not isinstance(messages, list):
        return None

    if hasattr(tokenizer, "apply_chat_template"):
        try:
            return tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=False,
            )
        except Exception as exc:
            logger.warning("Failed to apply chat template, falling back to plain messages: %s", exc)

    lines = []
    for message in messages:
        if not isinstance(message, dict):
            continue
        role = str(message.get("role", "user"))
        content = str(message.get("content", ""))
        lines.append(f"{role}: {content}")
    return "\n".join(lines)


def format_record(record: Mapping[str, object], tokenizer) -> Optional[str]:
    """
    Convert common SFT/calibration record formats to a single training string.

    Supported examples:
    - {"text": "..."}
    - {"prompt": "...", "response": "..."}
    - {"instruction": "...", "input": "...", "output": "..."}
    - {"question": "...", "answer": "..."}
    - {"messages": [{"role": "user", "content": "..."}, ...]}
    """
    messages_text = format_messages(record, tokenizer)
    if messages_text:
        return messages_text

    if isinstance(record.get("text"), str):
        return str(record["text"])

    prompt = record.get("prompt")
    response = record.get("response", record.get("completion", record.get("output")))
    if isinstance(prompt, str) and isinstance(response, str):
        return f"{prompt}\n{response}"
    if isinstance(prompt, str):
        return prompt

    instruction = record.get("instruction")
    output = record.get("output", record.get("answer", record.get("response")))
    input_text = record.get("input", "")
    if isinstance(instruction, str) and isinstance(output, str):
        if isinstance(input_text, str) and input_text.strip():
            return f"Instruction:\n{instruction}\n\nInput:\n{input_text}\n\nAnswer:\n{output}"
        return f"Instruction:\n{instruction}\n\nAnswer:\n{output}"

    question = record.get("question")
    answer = record.get("answer")
    if isinstance(question, str) and isinstance(answer, str):
        return f"Question:\n{question}\n\nAnswer:\n{answer}"
    if isinstance(question, str):
        return question

    return None


def load_text_examples(path: str, tokenizer, max_samples: Optional[int] = None) -> List[TextExample]:
    records = read_json_or_jsonl(path)
    examples: List[TextExample] = []

    for record in records:
        if isinstance(record, str):
            text = record
        elif isinstance(record, dict):
            text = format_record(record, tokenizer)
        else:
            text = None

        if text and text.strip():
            examples.append(TextExample(text=text))

        if max_samples is not None and len(examples) >= max_samples:
            break

    if not examples:
        raise ValueError(f"No usable text examples found in {path}")

    return examples


def resolve_torch_dtype(dtype: str):
    dtype = dtype.lower()
    if dtype == "auto":
        return "auto"
    if dtype in {"bf16", "bfloat16"}:
        return torch.bfloat16
    if dtype in {"fp16", "float16"}:
        return torch.float16
    if dtype in {"fp32", "float32"}:
        return torch.float32
    raise ValueError(f"Unsupported torch dtype: {dtype}")


def maybe_enable_gradient_checkpointing(model, enabled: bool) -> None:
    if not enabled:
        return
    if hasattr(model, "gradient_checkpointing_enable"):
        model.gradient_checkpointing_enable()
    if hasattr(model, "config"):
        model.config.use_cache = False


def log_rank_pattern_summary(rank_pattern: Mapping[str, int]) -> None:
    counts: MutableMapping[int, int] = {}
    for rank in rank_pattern.values():
        counts[int(rank)] = counts.get(int(rank), 0) + 1

    logger.info("Rank pattern modules: %d", len(rank_pattern))
    for rank in sorted(counts, reverse=True):
        logger.info("  rank %-4d -> %d modules", rank, counts[rank])


def train(args: argparse.Namespace) -> None:
    try:
        from peft import LoraConfig, TaskType, get_peft_model
        from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments, set_seed
    except ImportError as exc:
        raise ImportError(
            "train_adaptive_lora.py requires peft and transformers. "
            "Install them in the training environment before running this script."
        ) from exc

    set_seed(args.seed)

    logger.info("Loading tokenizer from %s", args.model_path)
    tokenizer = AutoTokenizer.from_pretrained(args.model_path, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    logger.info("Loading rank_map from %s", args.rank_map)
    rank_map = load_rank_map(args.rank_map)
    target_module_suffixes = parse_csv_list(args.target_modules)
    rank_pattern, alpha_pattern, lora_target_modules = build_rank_pattern(
        model_type=args.model_type,
        rank_map=rank_map,
        target_modules=target_module_suffixes,
        alpha_scale=args.lora_alpha_scale,
    )
    log_rank_pattern_summary(rank_pattern)
    logger.info("LoRA target modules from rank_map: %d", len(lora_target_modules))

    logger.info("Loading model from %s", args.model_path)
    model = AutoModelForCausalLM.from_pretrained(
        args.model_path,
        torch_dtype=resolve_torch_dtype(args.torch_dtype),
        device_map=args.device_map,
        trust_remote_code=True,
    )
    maybe_enable_gradient_checkpointing(model, args.gradient_checkpointing)
    validate_lora_targets_exist(model, lora_target_modules)

    lora_config = LoraConfig(
        r=args.default_rank,
        lora_alpha=args.default_alpha,
        target_modules=lora_target_modules,
        rank_pattern=rank_pattern,
        alpha_pattern=alpha_pattern,
        lora_dropout=args.lora_dropout,
        bias="none",
        task_type=TaskType.CAUSAL_LM,
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    logger.info("Loading training data from %s", args.train_file)
    examples = load_text_examples(args.train_file, tokenizer, max_samples=args.max_train_samples)
    train_dataset = CausalLMDataset(
        examples=examples,
        tokenizer=tokenizer,
        max_seq_length=args.max_seq_length,
        add_eos_token=not args.no_add_eos_token,
    )
    logger.info("Training examples: %d", len(train_dataset))

    data_collator = CausalLMDataCollator(tokenizer)

    training_args = TrainingArguments(
        output_dir=args.output_dir,
        overwrite_output_dir=args.overwrite_output_dir,
        num_train_epochs=args.num_train_epochs,
        max_steps=args.max_steps,
        per_device_train_batch_size=args.per_device_train_batch_size,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        learning_rate=args.learning_rate,
        weight_decay=args.weight_decay,
        warmup_ratio=args.warmup_ratio,
        lr_scheduler_type=args.lr_scheduler_type,
        logging_steps=args.logging_steps,
        save_steps=args.save_steps,
        save_total_limit=args.save_total_limit,
        bf16=args.bf16,
        fp16=args.fp16,
        gradient_checkpointing=args.gradient_checkpointing,
        report_to=args.report_to,
        remove_unused_columns=False,
        dataloader_num_workers=args.dataloader_num_workers,
        optim=args.optim,
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        data_collator=data_collator,
        tokenizer=tokenizer,
    )

    logger.info("Starting training")
    trainer.train(resume_from_checkpoint=args.resume_from_checkpoint)

    logger.info("Saving LoRA adapter to %s", args.output_dir)
    trainer.save_model(args.output_dir)
    tokenizer.save_pretrained(args.output_dir)

    metadata = {
        "base_model": args.model_path,
        "rank_map": args.rank_map,
        "model_type": args.model_type,
        "target_module_suffixes": target_module_suffixes,
        "target_module_count": len(lora_target_modules),
        "target_scope": "rank_map_modules_only",
        "lora_alpha_scale": args.lora_alpha_scale,
        "default_rank": args.default_rank,
        "default_alpha": args.default_alpha,
        "lora_dropout": args.lora_dropout,
        "max_seq_length": args.max_seq_length,
        "train_file": args.train_file,
    }
    metadata_path = os.path.join(args.output_dir, "adaptive_lora_train_info.json")
    with open(metadata_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2, ensure_ascii=False)
    logger.info("Saved training metadata to %s", metadata_path)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Train adaptive LoRA for a pruned MoE model.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    parser.add_argument("--model_path", required=True, help="Path to pruned base model.")
    parser.add_argument("--rank_map", required=True, help="Path to rank_map JSON.")
    parser.add_argument("--train_file", required=True, help="Training data JSON or JSONL.")
    parser.add_argument("--output_dir", required=True, help="Directory to save LoRA adapter.")
    parser.add_argument("--model_type", default="qwen3", choices=["qwen3", "deepseek"], help="Model module naming type.")

    parser.add_argument(
        "--target_modules",
        default="gate_proj,up_proj,down_proj",
        help="Comma-separated module suffixes under each retained expert.",
    )
    parser.add_argument("--default_rank", type=int, default=16, help="Fallback LoRA rank.")
    parser.add_argument("--default_alpha", type=int, default=32, help="Fallback LoRA alpha.")
    parser.add_argument("--lora_alpha_scale", type=float, default=2.0, help="alpha = rank * scale for rank_map modules.")
    parser.add_argument("--lora_dropout", type=float, default=0.05, help="LoRA dropout.")

    parser.add_argument("--max_seq_length", type=int, default=1024, help="Max training sequence length.")
    parser.add_argument("--max_train_samples", type=int, default=None, help="Optional debug sample limit.")
    parser.add_argument("--no_add_eos_token", action="store_true", help="Do not append eos token to each example.")

    parser.add_argument("--torch_dtype", default="auto", choices=["auto", "bf16", "bfloat16", "fp16", "float16", "fp32", "float32"])
    parser.add_argument("--device_map", default="auto", help="Device map for from_pretrained.")
    parser.add_argument("--gradient_checkpointing", action="store_true", help="Enable gradient checkpointing.")

    parser.add_argument("--num_train_epochs", type=float, default=1.0)
    parser.add_argument("--max_steps", type=int, default=-1, help="If > 0, overrides num_train_epochs.")
    parser.add_argument("--per_device_train_batch_size", type=int, default=1)
    parser.add_argument("--gradient_accumulation_steps", type=int, default=8)
    parser.add_argument("--learning_rate", type=float, default=2e-4)
    parser.add_argument("--weight_decay", type=float, default=0.0)
    parser.add_argument("--warmup_ratio", type=float, default=0.03)
    parser.add_argument("--lr_scheduler_type", default="cosine")
    parser.add_argument("--optim", default="adamw_torch")

    parser.add_argument("--logging_steps", type=int, default=10)
    parser.add_argument("--save_steps", type=int, default=100)
    parser.add_argument("--save_total_limit", type=int, default=2)
    parser.add_argument("--dataloader_num_workers", type=int, default=0)
    parser.add_argument("--report_to", default="none", help="Trainer report_to, e.g. none, tensorboard, wandb.")
    parser.add_argument("--bf16", action="store_true", help="Use bf16 training.")
    parser.add_argument("--fp16", action="store_true", help="Use fp16 training.")
    parser.add_argument("--overwrite_output_dir", action="store_true")
    parser.add_argument("--resume_from_checkpoint", default=None)
    parser.add_argument("--seed", type=int, default=42)

    return parser


def main() -> None:
    setup_logging()
    args = build_arg_parser().parse_args()

    if args.bf16 and args.fp16:
        raise ValueError("bf16 and fp16 cannot both be enabled.")
    if args.default_rank <= 0:
        raise ValueError("--default_rank must be positive.")
    if args.default_alpha <= 0:
        raise ValueError("--default_alpha must be positive.")

    train(args)


if __name__ == "__main__":
    main()
